### PR TITLE
Feature/tfg fixes

### PR DESCRIPTION
**Pull request by lordmortis**
bring in latest pikaday to this gem

### CODE REVIEW

**Comment by jordanmaguire** [comment]
I'm a big fan of having this setup 👍  I'd love this to open the doors to a conversation about using webpack/npm if that will allow us to use a Gemfile type deal for js

**Comment by BenR1312** [comment]
So is this a gem for our tfg work so we can stop throwing 1000 lines of pikaday js?

**Comment by lordmortis** [comment]
yes, that's exactly what this is for :D

**Comment by jordanmaguire** [comment]
> So is this a gem for our tfg work so we can stop throwing 1000 lines of pikaday js?

Correct

**Comment by pzi** [comment]
IMO, the readme should make it clear that this is not the original version but the forked one that adds time as well

**Comment by pzi** [comment]
> I'd love this to open the doors to a conversation about using webpack/npm if that will allow us to use a Gemfile type deal for js

npm uses package.json which is very similar to Gemfile(s) and I've seen rails projects starting to use that as well for vendor scripts.

**Comment by Ruxton** [comment]
I would 100% endorse switching to managing that stuff with webpack, npm or some shit over maintaining our own mini-gem. (that wont get maintained much) If the project is maintaining their own gem or someone is, then sweet use it.

**Comment by lordmortis** [comment]
@Ruxton So you'd prefer we pull in vendored javascript over doing it via Gems?

**Comment by pzi** [comment]
Conclusion?

**Pull request closed without merging**
